input {
  http {
    port => 5044
    #codec => json  # ← 這樣才能自動解析 JSON
  }
}

filter {
  json {
    source => "message"
    target => "parsed_json"
  }
  split {
    field => "parsed_json"
  }
  mutate {
    rename => {
      "[parsed_json][attack_prediction]" => "attack_prediction"
      "[parsed_json][URL]"               => "URL"
      "[parsed_json][description]"       => "description"
      "[parsed_json][return_code]"       => "return_code"
      "[parsed_json][log_record]"        => "log_record"
      "[parsed_json][Source]"            => "Source"
    }
  }
}

output {
  elasticsearch {
    hosts => ["elasticsearch:9200"]
    index => "prediction-logs-%{+YYYY.MM.dd}"
    document_id => "%{id}" #######新增 id 讓每筆資料都有一個獨立的 id
    action => "index" #############
    template_overwrite => true

    user => "elastic"
    password => "vEo4PSW2yMiHIMMTxAHk"  # 確保這裡的密碼
  }
  stdout { codec => rubydebug }
}