'use strict';
const $ = s => document.querySelector(s);
const labels = {'-1':'解析失敗',0:'正常',1:'SQL Injection',2:'XSS',3:'Directory Traversal',4:'WAF 規則命中'};
const statusNames = {new:'待調查',investigating:'調查中',resolved:'已處理',false_positive:'誤報'};
const titles = {overview:'安全總覽',logs:'日誌中心',incidents:'告警與事件',topology:'關聯拓樸',services:'受保護服務',blacklist:'封鎖管理',rules:'偵測規則',audit:'操作紀錄',users:'使用者管理',settings:'系統設定',account:'我的帳號',intel:'情資管理','intel-news':'近期資安動態',assistant:'NCU SOC AI 防禦小精靈'};
const colors = {'-1':'#9c8b8b',0:'#6b9eae',1:'#cb6a76',2:'#d4a54c',3:'#8a84bc',4:'#b35f93'};
const geminiModels=[
  ['gemini-3.5-flash-lite','Gemini 3.5 Flash Lite｜最省成本・推薦'],
  ['gemini-3.1-flash-lite','Gemini 3.1 Flash Lite｜低成本・高峰可能忙碌'],
  ['gemini-3.5-flash','Gemini 3.5 Flash｜較強推理']
];
const aiModelOptions=(provider,current)=>provider==='gemini'?geminiModels.map(([id,label])=>`<option value="${id}" ${current===id?'selected':''}>${label}</option>`).join(''):`<option value="${esc(current||'gpt-4o-mini')}">${esc(current||'gpt-4o-mini')}</option>`;
let page = 'overview', logPage=1, incidentPage=1, overviewData=null, requestVersion=0, trafficMode='total', mapMode='total', topologyMode='links';
let logFilters = {q:'',src_ip:'',attack:'',status:'',since:'',until:''}, incidentStatus='';
let intelFilters={q:'',kind:'',verdict:'',page:1,sort:'last_seen'}, intelNewsPage=1;
let worldMapPromise;
let currentUser=null;
let sessionDeadline=0,sessionAbsoluteDeadline=0,sessionWarningSeconds=300,lastActivityReport=0,sessionExpired=false;
const esc = v => String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function markdown(value){
  const inline=text=>esc(text)
    .replace(/`([^`]+)`/g,'<code>$1</code>')
    .replace(/\*\*([^*]+)\*\*/g,'<strong>$1</strong>')
    .replace(/\*([^*]+)\*/g,'<em>$1</em>')
    .replace(/\[([^\]]+)\]\((https?:\/\/[^\s)]+)\)/g,'<a href="$2" target="_blank" rel="noopener noreferrer">$1</a>');
  const lines=String(value??'').replace(/\r/g,'').split('\n'),out=[];let list='',code=false,codeLines=[];
  const closeList=()=>{if(list){out.push(`</${list}>`);list='';}};
  for(const line of lines){
    if(line.trim().startsWith('```')){closeList();if(code){out.push(`<pre><code>${esc(codeLines.join('\n'))}</code></pre>`);codeLines=[];}code=!code;continue;}
    if(code){codeLines.push(line);continue;}
    const heading=line.match(/^(#{1,3})\s+(.+)$/),bullet=line.match(/^\s*[-*]\s+(.+)$/),ordered=line.match(/^\s*\d+[.)]\s+(.+)$/);
    if(heading){closeList();out.push(`<h${heading[1].length}>${inline(heading[2])}</h${heading[1].length}>`);continue;}
    if(bullet||ordered){const next=bullet?'ul':'ol';if(list!==next){closeList();list=next;out.push(`<${list}>`);}out.push(`<li>${inline((bullet||ordered)[1])}</li>`);continue;}
    closeList();out.push(line.trim()?`<p>${inline(line)}</p>`:'<br>');
  }
  closeList();if(codeLines.length)out.push(`<pre><code>${esc(codeLines.join('\n'))}</code></pre>`);return out.join('');
}
const num = n => Number(n||0).toLocaleString('zh-TW');
const time = v => v ? new Date(v).toLocaleString('zh-TW',{hour12:false}) : '尚無資料';
const badge = code => `<span class="badge a${Number(code)}">${esc(labels[code]||'未知')}</span>`;
const detector = r => {
  const sources = Array.isArray(r.detector_sources) ? r.detector_sources.map(String)
    : (r.detector_sources ? String(r.detector_sources).split(/[,+|]/).map(s=>s.trim().toLowerCase()) : []);
  if (!sources.length) sources.push(r.origin === 'modsecurity-crs' ? 'waf' : 'ml');
  const hasWaf = sources.some(s=>s.includes('waf')||s.includes('crs'));
  const hasMl = sources.some(s=>s==='ml'||s.includes('machine'));
  if (hasWaf && hasMl) return '<span class="detector both">WAF + ML</span>';
  return hasWaf ? '<span class="detector waf">WAF / CRS</span>' : '<span class="detector ml">ML</span>';
};
const empty = (title,text) => `<div class="empty"><strong>${esc(title)}</strong>${esc(text)}</div>`;
const panel = (title,subtitle,body,extra='') => `<div class="panel"><div class="panel-head"><div><h2>${title}</h2><small>${subtitle}</small></div>${extra}</div>${body}</div>`;
async function api(path, options={}) {
  const response = await fetch('/api'+path,{...options,headers:{'Content-Type':'application/json','X-SIEM-Request':'dashboard',...options.headers}});
  let data;try{data=await response.json();}catch{}
  if(response.status===401&&path!=='/auth/login')showLogin(typeof data?.detail==='string'?data.detail:'登入已逾期，請重新登入');
  if(!response.ok)throw new Error(typeof data?.detail==='string'?data.detail:`操作失敗（${response.status}），請檢查輸入與服務狀態。`);
  return data;
}
function fail(error){$('#error').textContent=error.message;$('#error').hidden=false;}
function toast(text){$('#toast').textContent=text;$('#toast').hidden=false;setTimeout(()=>$('#toast').hidden=true,3500);}
function query(){const p=new URLSearchParams({hours:$('#range').value});for(const [k,v] of Object.entries(logFilters)){if(v!=='')p.set(k,(k==='since'||k==='until')?new Date(v).toISOString():v);}return p;}
function tableEvents(rows){
  if(!rows.length)return empty('沒有符合條件的日誌','調整時間或篩選條件，或啟動日誌收集器。');
  return `<div class="table-wrap"><table><thead><tr><th>時間</th><th>來源 IP</th><th>目的地</th><th>受保護服務</th><th>偵測來源</th><th>偵測分類</th><th>請求路徑</th><th>HTTP</th><th></th></tr></thead><tbody>${rows.map(r=>`<tr><td>${time(r.timestamp)}</td><td class="mono">${esc(r.src_ip)}${r.src_port?':'+esc(r.src_port):''}</td><td class="mono">${esc(r.dst_ip||r.service_host||'127.0.0.1')}:${esc(r.service_port||80)}</td><td>${esc(r.service_name||r.target)}</td><td>${detector(r)}</td><td>${badge(r.attack)}</td><td class="url-cell" title="${esc(r.url)}"><span class="muted">${esc(r.method)}</span> ${esc(r.url)}</td><td>${r.status||'—'}</td><td><button class="secondary" data-event="${esc(r.id)}">詳情</button></td></tr>`).join('')}</tbody></table></div>`;
}
function chart(rows,unit='hour',mode='total'){
  if(!rows.length)return empty('等待日誌資料','收到日誌後，這裡會顯示每小時請求與攻擊趨勢。');
  const metric=mode==='attacks'?'attacks':mode==='normal'?'normal':'total', w=700,h=205,left=42,right=10,top=16,base=168;
  // Aggregate to at most 48 columns for long date ranges.
  const step=Math.max(1,Math.ceil(rows.length/48)),bins=[];
  for(let i=0;i<rows.length;i+=step){const group=rows.slice(i,i+step);bins.push({bucket:group[0].bucket,total:group.reduce((s,r)=>s+r.total,0),attacks:group.reduce((s,r)=>s+r.attacks,0),normal:group.reduce((s,r)=>s+(r.normal||0),0),sources:Math.max(...group.map(r=>r.sources||0))});}
  const peak=Math.max(...bins.map(r=>r[metric]),1),slot=(w-left-right)/bins.length;
  let svg=`<svg class="chart" viewBox="0 0 ${w} ${h}" role="img" aria-label="請求與攻擊趨勢，依時間分組">`;
  for(let j=0;j<4;j++){const y=top+(base-top)*j/3;svg+=`<line class="chart-grid" x1="${left}" x2="${w}" y1="${y}" y2="${y}"/><text x="0" y="${y+4}">${num(Math.round(peak*(1-j/3)))}</text>`;}
  bins.forEach((r,i)=>{const x=left+i*slot+slot*.14,bw=Math.max(2,slot*.72),height=r[metric]/peak*(base-top),fill=metric==='attacks'?'#c76a76':metric==='normal'?'#65a39c':'#729bc2';svg+=`<g><title>${esc(r.bucket)} UTC：${num(r.total)} 總流量，${num(r.attacks)} 攻擊，${num(r.sources)} 個來源</title><rect x="${x}" y="${base-height}" width="${bw}" height="${height}" rx="2" fill="${fill}"/></g>`;if(i===0||i===bins.length-1||i===Math.floor(bins.length/2)){const stamp=r.bucket.length===10?r.bucket+'T00:00:00Z':r.bucket.length===13?r.bucket+':00:00Z':r.bucket+':00Z';svg+=`<text x="${x}" y="194" text-anchor="${i===bins.length-1?'end':'start'}">${esc(new Date(stamp).toLocaleString('zh-TW',{month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hour12:false}))}</text>`;}});
  return svg+'</svg>';
}
function distribution(data){const total=data.counts.total;return `<div class="panel-body distribution">${Object.entries(labels).filter(([k])=>k!=='-1'||data.counts.errors).map(([code,label])=>{const n=data.types.find(r=>r.attack===Number(code))?.count||0;return `<div class="distribution-row"><div class="row"><span>${esc(label)}</span><span>${num(n)} <span class="muted">${total?(n/total*100).toFixed(1):'0'}%</span></span></div><div class="bar-track"><div class="bar-fill" style="width:${total?n/total*100:0}%;background:${colors[code]}"></div></div></div>`;}).join('')}</div>`;}
async function loadWorldMap(){if(!worldMapPromise)worldMapPromise=fetch('/static/world-countries.geojson').then(r=>{if(!r.ok)throw new Error('世界地圖資料載入失敗');return r.json();});return worldMapPromise;}
function worldMap(data,mapData,mode='total'){
  const allPoints=data.points||[],points=allPoints.filter(p=>mode==='attacks'?Number(p.attacks)>0:mode==='normal'?Number(p.total)-Number(p.attacks)>0:true),w=800,h=360,project=(lat,lon)=>[(Number(lon)+180)/360*w,(90-Number(lat))/180*h];
  const ringPath=ring=>{let d='',lastX=null;for(const coord of ring){const [x,y]=project(coord[1],coord[0]),jump=lastX!==null&&Math.abs(x-lastX)>w/2;d+=(lastX===null||jump?`${jump?'Z ':''}M${x.toFixed(1)} ${y.toFixed(1)}`:` L${x.toFixed(1)} ${y.toFixed(1)}`);lastX=x;}return d+'Z';};
  const countryPaths=(mapData?.features||[]).map(f=>{const g=f.geometry;if(!g)return '';const polygons=g.type==='Polygon'?[g.coordinates]:g.type==='MultiPolygon'?g.coordinates:[];const d=polygons.flatMap(p=>p.map(ringPath)).join(' ');return `<path d="${d}" data-country="${esc(f.properties?.ADM0_A3||'')}"/>`;}).join('');
  const [tx,ty]=project(23.5,121),defs=`<defs><filter id="mapGlow"><feGaussianBlur stdDeviation="3" result="b"/><feMerge><feMergeNode in="b"/><feMergeNode in="SourceGraphic"/></feMerge></filter><marker id="arrowNormal" markerWidth="7" markerHeight="7" refX="6" refY="3.5" orient="auto"><path d="M0 0L7 3.5L0 7Z" fill="#54b8ff"/></marker><marker id="arrowAttack" markerWidth="7" markerHeight="7" refX="6" refY="3.5" orient="auto"><path d="M0 0L7 3.5L0 7Z" fill="#ff5968"/></marker></defs>`;
  let svg=`<svg class="world-map" viewBox="0 0 ${w} ${h}" role="img" aria-label="全球來源 IP 動態流量分布">${defs}<rect width="800" height="360" fill="#122c40"/><g class="map-grid">${[60,120,180,240,300].map(y=>`<path d="M0 ${y}H800"/>`).join('')}${[100,200,300,400,500,600,700].map(x=>`<path d="M${x} 0V360"/>`).join('')}</g><g class="countries">${countryPaths}</g><g class="geo-flows">`;
  for(const p of points){const [x,y]=project(p.latitude,p.longitude),normal=Math.max(0,Number(p.total)-Number(p.attacks)),attacks=Number(p.attacks),curve=(x<tx?-1:1)*(24+Math.abs(x-tx)*.04),cx=(x+tx)/2,cy=Math.min(y,ty)-curve;if(normal&&mode!=='attacks')svg+=`<path class="geo-flow normal" d="M${x} ${y} Q${cx.toFixed(1)} ${cy.toFixed(1)} ${tx} ${ty}" marker-end="url(#arrowNormal)"><title>${esc(p.src_ip)} 正常流量 ${num(normal)}</title></path>`;if(attacks&&mode!=='normal')svg+=`<path class="geo-flow attack" d="M${x} ${y} Q${cx.toFixed(1)} ${(cy-7).toFixed(1)} ${tx} ${ty}" marker-end="url(#arrowAttack)"><title>${esc(p.src_ip)} 攻擊流量 ${num(attacks)}</title></path>`;}
  svg+='</g>';
  for(const p of points){const [x,y]=project(p.latitude,p.longitude),normal=Math.max(0,Number(p.total)-Number(p.attacks)),attacks=Number(p.attacks),r=Math.min(12,5+Math.log2(Number(p.total)+1)),common=`data-ip="${esc(p.src_ip)}" tabindex="0" role="button"`;if(normal&&mode!=='attacks')svg+=`<g class="geo-point normal" ${common} aria-label="查看 ${esc(p.src_ip)} 的正常流量"><title>${esc(p.src_ip)} · ${esc(p.city||p.country)} · ${num(normal)} 正常流量</title><circle class="pulse" cx="${x}" cy="${y}" r="${r+7}"/><circle cx="${x}" cy="${y}" r="${r}"/></g>`;if(attacks&&mode!=='normal')svg+=`<g class="geo-point attack" ${common} aria-label="查看 ${esc(p.src_ip)} 的攻擊流量"><title>${esc(p.src_ip)} · ${esc(p.city||p.country)} · ${num(attacks)} 攻擊流量</title><circle class="pulse" cx="${x+4}" cy="${y-4}" r="${r+7}"/><circle cx="${x+4}" cy="${y-4}" r="${r}"/></g>`;}
  return svg+`<g class="map-destination"><circle class="pulse" cx="${tx}" cy="${ty}" r="15"/><circle cx="${tx}" cy="${ty}" r="7"/><text x="${tx+12}" y="${ty-10}">NCU SIEM</text></g></svg>`;
}
function topology(data){
  const edges=data.edges||[];
  if(!edges.length)return empty('尚無流量關聯','開始收集 Apache 日誌後，即可查看來源 IP 與受保護服務的關聯。');
  const height=Math.max(360,edges.length*65+35),targets=[...new Set(edges.map(e=>e.target))];
  const targetY=new Map(targets.map((t,i)=>[t,height*(i+1)/(targets.length+1)]));
  const blocked=new Set(data.blocked.map(b=>typeof b==='string'?b:b.ip));
  let svg=`<svg class="topology" viewBox="0 0 860 ${height}" role="img" aria-label="來源 IP 與受保護服務的日誌關聯圖"><text x="35" y="20" font-size="12" fill="#687b92">來源 IP</text><text x="605" y="20" font-size="12" fill="#687b92">受保護服務</text>`;
  edges.forEach((e,i)=>{const y=55+i*65,ty=targetY.get(e.target);svg+=`<path class="edge ${e.attacks?'attack':''}" d="M 240 ${y} C 410 ${y},440 ${ty},605 ${ty}" stroke-width="${Math.min(8,1+Math.log2(e.total+1))}"/><g class="ip-node" data-ip="${esc(e.src_ip)}" tabindex="0" role="button" aria-label="查看 ${esc(e.src_ip)} 的日誌"><rect x="30" y="${y-21}" width="210" height="44" rx="5" fill="${blocked.has(e.src_ip)?'#fff0f1':'#f5f8fc'}" stroke="#d9e3ed"/><circle cx="48" cy="${y}" r="4" fill="${e.attacks?'#c96a76':'#57969b'}"/><text x="62" y="${y-2}" font-size="13" fill="#20334e">${esc(e.src_ip)}${blocked.has(e.src_ip)?' ⊘':''}</text><text x="62" y="${y+13}" font-size="10" fill="#687b92">${num(e.total)} 請求 / ${num(e.attacks)} 攻擊</text></g>`;});
  targets.forEach(t=>{const y=targetY.get(t);svg+=`<g><rect x="605" y="${y-33}" width="225" height="66" rx="7" fill="#203d61"/><text x="627" y="${y-6}" font-size="13" fill="white">${esc(t.length>24?t.slice(0,24)+'…':t)}</text><text x="627" y="${y+15}" font-size="11" fill="#b4cee8">Apache · HTTP</text></g>`;});return svg+'</svg>';
}
function nebulaTopology(data){
  const edges=data.edges||[];
  if(!edges.length)return empty('尚無流量關聯','收到受保護服務的日誌後，星雲圖會顯示來源與攻擊路徑。');
  const w=960,h=600,cx=w/2,cy=h/2,blocked=new Set(data.blocked.map(b=>typeof b==='string'?b:b.ip));
  const targets=[...new Set(edges.map(e=>e.target))],sources=[...new Set(edges.map(e=>e.src_ip))];
  const polar=(radius,index,total,offset=-Math.PI/2)=>({x:cx+Math.cos(offset+index*Math.PI*2/Math.max(total,1))*radius,y:cy+Math.sin(offset+index*Math.PI*2/Math.max(total,1))*radius});
  const targetPos=new Map(targets.map((t,i)=>[t,polar(Math.min(165,95+targets.length*10),i,targets.length)]));
  const sourcePos=new Map(sources.map((ip,i)=>[ip,polar(Math.min(270,210+sources.length*2.5),i,sources.length,-Math.PI/2.35)]));
  const sourceTotals=new Map(sources.map(ip=>[ip,edges.filter(e=>e.src_ip===ip).reduce((s,e)=>s+Number(e.total||0),0)]));
  let svg=`<div class="nebula-stage"><svg class="nebula" viewBox="0 0 ${w} ${h}" role="img" aria-label="來源 IP、受保護服務與 SIEM 的星雲關聯圖"><defs><radialGradient id="space" cx="50%" cy="48%"><stop offset="0" stop-color="#173e5d"/><stop offset=".5" stop-color="#0d263d"/><stop offset="1" stop-color="#071827"/></radialGradient><filter id="glow"><feGaussianBlur stdDeviation="4" result="blur"/><feMerge><feMergeNode in="blur"/><feMergeNode in="SourceGraphic"/></feMerge></filter></defs><rect width="${w}" height="${h}" rx="8" fill="url(#space)"/><g class="nebula-stars">${Array.from({length:54},(_,i)=>{const x=(i*137+31)%w,y=(i*83+47)%h,r=i%9===0?1.4:.7;return `<circle cx="${x}" cy="${y}" r="${r}"/>`;}).join('')}</g><circle class="orbit" cx="${cx}" cy="${cy}" r="${Math.min(165,95+targets.length*10)}"/><circle class="orbit outer" cx="${cx}" cy="${cy}" r="${Math.min(270,210+sources.length*2.5)}"/>`;
  edges.forEach(e=>{const a=sourcePos.get(e.src_ip),b=targetPos.get(e.target),attack=Number(e.attacks)>0;svg+=`<path class="nebula-edge ${attack?'attack':''}" d="M${a.x.toFixed(1)} ${a.y.toFixed(1)} Q${cx} ${cy} ${b.x.toFixed(1)} ${b.y.toFixed(1)}" stroke-width="${Math.min(7,1+Math.log2(Number(e.total)+1)*.65)}"><title>${esc(e.src_ip)} → ${esc(e.target)}：${num(e.total)} 流量 / ${num(e.attacks)} 攻擊</title></path>`;});
  svg+=`<g class="siem-core"><circle cx="${cx}" cy="${cy}" r="48"/><circle class="core-ring" cx="${cx}" cy="${cy}" r="59"/><text x="${cx}" y="${cy-2}" text-anchor="middle">mini SIEM</text><text class="sub" x="${cx}" y="${cy+17}" text-anchor="middle">NCU-PDCLAB</text></g>`;
  targets.forEach(t=>{const p=targetPos.get(t),short=t.length>19?t.slice(0,19)+'…':t;svg+=`<g class="service-star"><circle cx="${p.x}" cy="${p.y}" r="25"/><circle class="service-ring" cx="${p.x}" cy="${p.y}" r="31"/><text x="${p.x}" y="${p.y+43}" text-anchor="middle">${esc(short)}</text><title>受保護服務：${esc(t)}</title></g>`;});
  sources.forEach(ip=>{const p=sourcePos.get(ip),related=edges.filter(e=>e.src_ip===ip),attacks=related.reduce((s,e)=>s+Number(e.attacks||0),0),r=Math.min(15,6+Math.log2(sourceTotals.get(ip)+1));svg+=`<g class="ip-node nebula-source ${attacks?'hostile':''} ${blocked.has(ip)?'blocked':''}" data-ip="${esc(ip)}" tabindex="0" role="button" aria-label="查看 ${esc(ip)} 的日誌"><circle class="source-halo" cx="${p.x}" cy="${p.y}" r="${r+7}"/><circle cx="${p.x}" cy="${p.y}" r="${r}"/><text x="${p.x}" y="${p.y+r+16}" text-anchor="middle">${esc(ip)}${blocked.has(ip)?' ⊘':''}</text><title>${esc(ip)}：${num(sourceTotals.get(ip))} 請求 / ${num(attacks)} 攻擊</title></g>`;});
  return svg+'</svg><div class="nebula-key"><span><i class="core"></i>SIEM</span><span><i class="service"></i>受保護服務</span><span><i class="source"></i>正常來源</span><span><i class="threat"></i>攻擊來源</span></div></div>';
}
async function render(){
  const version=++requestVersion;$('#error').hidden=true;
  try{
    const data=await api('/overview?hours='+$('#range').value);if(version!==requestVersion)return;overviewData=data;
    const collector=data.collector,live=collector.status==='watching'&&Date.now()-Date.parse(collector.heartbeat)<30000;
    $('#health').textContent=live?'日誌收集器運作中':collector.status==='error'?'收集器異常：'+collector.error:'日誌收集器未連線 · 可查閱已儲存資料';
    $('#updated').textContent='更新於 '+new Date().toLocaleTimeString('zh-TW',{hour12:false});
    let html='';
    if(page==='overview'){
      const recent=await api('/events?hours='+$('#range').value+'&page_size=7');
      const [geo,mapData]=await Promise.all([api('/geo-map?hours='+$('#range').value),loadWorldMap()]);
      html=`<div class="metrics">${[['接收日誌',data.counts.total,'所選時間範圍',''],['攻擊偵測',data.counts.attacks,'ML 分類為異常的請求','attack'],['待處理事件',data.counts.open_incidents,'所有時間 · 待調查與調查中','pending'],['來源 IP',data.counts.sources,`${data.blocked.length} 個 IP 已封鎖`,'']].map(([l,n,s,c])=>`<div class="metric ${c}"><div class="metric-label">${l}</div><div class="metric-number">${num(n)}</div><small>${s}</small></div>`).join('')}</div>`;
      const unitName={minute:'每分鐘',hour:'每小時',day:'每日'}[data.timeline_unit]||'依時間';
      const trafficControls=`<div class="traffic-controls" role="group" aria-label="流量類型"><button class="secondary ${trafficMode==='total'?'active':''}" data-traffic-mode="total">總流量</button><button class="secondary ${trafficMode==='attacks'?'active':''}" data-traffic-mode="attacks">偵測為攻擊</button><button class="secondary ${trafficMode==='normal'?'active':''}" data-traffic-mode="normal">正常流量</button></div>`;
      const mapControls=`<div class="map-toolbar"><div class="map-legend"><span><i class="normal"></i>正常流量</span><span><i class="attack"></i>攻擊流量</span><span><i class="destination"></i>NCU SIEM</span></div><div class="traffic-controls" role="group" aria-label="地圖流量類型"><button class="secondary ${mapMode==='total'?'active':''}" data-map-mode="total">全部</button><button class="secondary ${mapMode==='attacks'?'active':''}" data-map-mode="attacks">只顯示攻擊</button><button class="secondary ${mapMode==='normal'?'active':''}" data-map-mode="normal">只顯示正常</button></div></div>`;
      const mapPoints=(geo.points||[]).filter(p=>mapMode==='attacks'?Number(p.attacks)>0:mapMode==='normal'?Number(p.total)-Number(p.attacks)>0:true);
      const mapCountries=[...mapPoints.reduce((m,p)=>{const key=p.country_code||'??',row=m.get(key)||{country_code:key,country:p.country||'Unknown',total:0,attacks:0};row.total+=Number(p.total)||0;row.attacks+=Number(p.attacks)||0;m.set(key,row);return m;},new Map()).values()].sort((a,b)=>mapMode==='normal'?(b.total-b.attacks)-(a.total-a.attacks):mapMode==='attacks'?b.attacks-a.attacks:b.total-a.total);
      const top=data.ddos?.top_source;
      html+=`<div class="ddos-strip"><div><span>峰值流量</span><strong>${num(data.ddos?.peak_per_bucket||0)}</strong><small>${unitName}請求數；突增時需調查</small></div><div><span>攻擊比例</span><strong>${data.counts.total?(data.counts.attacks/data.counts.total*100).toFixed(1):'0.0'}%</strong><small>ML 判定攻擊／總流量</small></div><div><span>最活躍來源</span><strong class="mono">${esc(top?.src_ip||'—')}</strong><small>${top?`${num(top.total)} 次請求，${num(top.attacks)} 次攻擊`:'所選範圍沒有流量'}</small></div></div>`;
      html+=panel('WAF 防護狀態','OWASP CRS Gateway · Detection Only',`<div class="waf-status"><div><span class="waf-dot"></span><strong>運作中</strong><small>CRS PL1 · 異常分數記錄</small></div><div><b>Apache</b><small>入口 :80</small></div><div><b>Flask</b><small>入口 :8081</small></div><div><b>Django</b><small>入口 :8082</small></div><p>WAF 規則命中會與應用程式日誌合併，並保留 CRS rule ID 作為調查證據。</p></div>`);
      html+=`<div class="grid">${panel('流量時間軸',`${unitName}彙整 · 可切換人工檢視`, `<div class="panel-body">${trafficControls}${chart(data.timeline,data.timeline_unit,trafficMode)}</div>`)}${panel('偵測分類','機器學習辨識結果',distribution(data))}</div>`;
      html+=panel('全球來源分布',`${mapPoints.length} 個符合篩選的已定位來源 · ${geo.pending} 個等待比對`,`${mapControls}<div class="geo-layout"><div>${worldMap(geo,mapData,mapMode)}</div><div class="country-list">${mapCountries.length?mapCountries.slice(0,8).map(c=>{const unavailable=c.country_code==='??'||c.country==='Unknown',normal=Math.max(0,c.total-c.attacks);return `<div><strong>${esc(unavailable?'—':c.country_code)}</strong><span>${esc(unavailable?'無法定位':c.country)}<small><b class="normal-text">${num(normal)} 正常</b> / <b class="attack-text">${num(c.attacks)} 攻擊</b></small></span></div>`;}).join(''):empty('此篩選沒有流量','切換上方條件查看其他已定位來源。')}</div></div>`);
      html+=panel('最新日誌','追蹤請求，查看原始證據',tableEvents(recent.items),'<a href="#logs">查看全部</a>');
    }else if(page==='logs'){
      const p=query();p.set('page',logPage);const result=await api('/events?'+p);
      const opts=(obj,selected)=>Object.entries(obj).map(([k,v])=>`<option value="${k}" ${String(selected)===k?'selected':''}>${v}</option>`).join('');
      html=panel('日誌搜尋','查詢原始請求與模型判斷',`<form id="log-search" class="filters"><label class="search">關鍵字<input name="q" value="${esc(logFilters.q)}" placeholder="搜尋路徑、payload 或原始日誌"></label><label>來源 IP<input name="src_ip" value="${esc(logFilters.src_ip)}" placeholder="例如 192.0.2.10"></label><label>偵測分類<select name="attack"><option value="">全部分類</option>${opts(labels,logFilters.attack)}</select></label><label>HTTP 狀態<input name="status" type="number" min="100" max="599" value="${esc(logFilters.status)}" placeholder="全部"></label><label>開始時間<input name="since" type="datetime-local" value="${esc(logFilters.since)}"></label><label>結束時間<input name="until" type="datetime-local" value="${esc(logFilters.until)}"></label><button>搜尋</button><button type="button" class="secondary" id="clear-filters">清除</button></form>${tableEvents(result.items)}<div class="pagination"><span>共 ${num(result.total)} 筆</span><div><button class="secondary" data-log-page="${logPage-1}" ${logPage<=1?'disabled':''}>上一頁</button><span>${logPage} / ${Math.max(1,Math.ceil(result.total/50))}</span><button class="secondary" data-log-page="${logPage+1}" ${logPage*50>=result.total?'disabled':''}>下一頁</button></div></div>`,`<a href="/api/events/export?${esc(query())}">匯出 CSV</a>`);
    }else if(page==='topology'){
      const topologyTabs=`<div class="view-tabs" role="tablist" aria-label="拓樸圖顯示模式"><button role="tab" aria-selected="${topologyMode==='links'}" class="${topologyMode==='links'?'active':''}" data-topology-mode="links">關聯拓樸</button><button role="tab" aria-selected="${topologyMode==='nebula'}" class="${topologyMode==='nebula'?'active':''}" data-topology-mode="nebula">星雲圖</button></div>`;
      html='<div class="notice">節點與連線使用相同的即時日誌資料；點選來源 IP 可直接前往該來源的日誌。</div>';
      html+=panel(topologyMode==='nebula'?'攻擊關聯星雲':'流量關聯圖',`所選範圍內共 ${num(data.counts.sources)} 個來源 IP`,`${topologyTabs}<div class="panel-body topology-view">${topologyMode==='nebula'?nebulaTopology(data):topology(data)}</div>`,topologyMode==='links'?'<div class="legend"><span><i></i>流量</span><span><i class="red"></i>含攻擊</span></div>':'');
    }else if(page==='incidents'){
      const result=await api('/incidents?status='+incidentStatus+'&page='+incidentPage+'&hours='+$('#range').value);
      html='<div class="notice">待調查與調查中的事件會持續保留在工作佇列，不受右上角時間範圍影響；已處理與誤報事件才依資料範圍顯示。篩選不會刪除資料。</div>';
      html+=panel('事件工作佇列','調查、註記與處理安全事件',`<div class="filters"><label>處理狀態<select id="incident-status"><option value="">全部</option>${Object.entries(statusNames).map(([k,v])=>`<option value="${k}" ${incidentStatus===k?'selected':''}>${v}</option>`).join('')}</select></label></div>${result.items.length?`<div class="table-wrap"><table><thead><tr><th>事件</th><th>來源 IP</th><th>嚴重度</th><th>命中</th><th>狀態</th><th>處理者</th><th>處理時間</th><th>建立時間</th><th></th></tr></thead><tbody>${result.items.map(r=>`<tr><td>#${r.id} ${esc(r.rule_name)}</td><td class="mono">${esc(r.src_ip)}</td><td><span class="badge ${esc(r.severity)}">${esc(r.severity)}</span></td><td>${r.count}</td><td><span class="badge ${r.status}">${statusNames[r.status]}</span></td><td>${esc(r.handled_by||'未記錄')}</td><td>${r.handled_at?time(r.handled_at):'—'}</td><td>${time(r.created_at)}</td><td><button class="secondary" data-incident="${r.id}">調查</button></td></tr>`).join('')}</tbody></table></div>`:empty('目前沒有符合條件的事件','啟用規則後，新收到的日誌符合條件時會建立事件。')}<div class="pagination"><span>${num(result.total)} 個事件</span><div><button class="secondary" data-incident-page="${incidentPage-1}" ${incidentPage<=1?'disabled':''}>上一頁</button><span>${incidentPage}</span><button class="secondary" data-incident-page="${incidentPage+1}" ${incidentPage*50>=result.total?'disabled':''}>下一頁</button></div></div>`);
    }else if(page==='services'){
      const rows=await api('/protected-services');
      const kindOptions=(value)=>['apache','nginx','iis','flask','django','other'].map(k=>`<option value="${k}" ${value===k?'selected':''}>${k}</option>`).join('');
      const parserOptions=(value)=>[['apache_combined','Apache Combined'],['flask_json','Flask JSON'],['django_json','Django JSON']].map(([k,v])=>`<option value="${k}" ${value===k?'selected':''}>${v}</option>`).join('');
      const serviceRow=r=>`<details class="service-item"><summary><span class="rule-chevron">›</span><span class="mono rule-id">${esc(r.service_uid)}</span><strong>${esc(r.name)}</strong><span>${esc(r.kind)}</span><span class="mono">${esc(r.host)}:${r.port}</span><span>${r.waf_enabled?'<span class="detector waf">WAF</span>':'—'}</span><span class="rule-state ${r.enabled?'on':'off'}">${r.enabled?'監控中':'已停用'}</span></summary><form class="service-editor" data-service="${r.id}"><p>Collector 監控 <span class="mono">${esc(r.log_path)}</span>${r.waf_enabled?`，並讀取 WAF audit log <span class="mono">${esc(r.waf_log_path)}</span>`:''}。</p><div class="service-fields"><label>服務名稱<input name="name" required maxlength="100" value="${esc(r.name)}"></label><label>Server 類型<select name="kind">${kindOptions(r.kind)}</select></label><label>IP／Host<input name="host" required maxlength="255" value="${esc(r.host)}"></label><label>Port<input name="port" type="number" min="1" max="65535" required value="${r.port}"></label><label class="wide">Access log 路徑<input name="log_path" required maxlength="500" value="${esc(r.log_path)}"></label><label>Parser 格式<select name="parser_format">${parserOptions(r.parser_format)}</select></label><label class="check">啟用監控<input type="checkbox" name="enabled" ${r.enabled?'checked':''}></label><label class="wide">WAF audit log 路徑<input name="waf_log_path" maxlength="500" value="${esc(r.waf_log_path||'')}"></label><label class="check">啟用 WAF 日誌<input type="checkbox" name="waf_enabled" ${r.waf_enabled?'checked':''}></label></div><div class="detail-actions"><button>儲存變更</button><button type="button" class="secondary" data-delete-service="${r.id}">移除服務</button></div></form></details>`;
      html='<div class="notice">受保護服務是實際被監控的 Web Server；WAF 僅是入口防護層。Log 路徑必須位於目前專案目錄內，新增或停用後 collector 會自動更新。</div>';
      html+=`<details class="panel create-panel"><summary><strong>新增受保護服務</strong><small>系統自動配置 SVC 規則 ID</small></summary><form id="new-service-form" class="service-fields service-create"><label>服務名稱<input name="name" required maxlength="100" placeholder="例如：內部 API 服務"></label><label>Server 類型<select name="kind">${kindOptions('other')}</select></label><label>IP／Host<input name="host" required value="127.0.0.1"></label><label>Port<input name="port" type="number" min="1" max="65535" required value="8083"></label><label class="wide">Access log 路徑<input name="log_path" required placeholder="logs/service-4/access.log"></label><label>Parser 格式<select name="parser_format">${parserOptions('apache_combined')}</select></label><label class="check">啟用監控<input type="checkbox" name="enabled" checked></label><label class="wide">WAF audit log 路徑<input name="waf_log_path" placeholder="選填，例如 logs/waf/service-4/audit.jsonl"></label><label class="check">啟用 WAF 日誌<input type="checkbox" name="waf_enabled"></label><button>新增服務</button></form></details>`;
      html+=`<div class="service-title"><div><h2>服務清單</h2><small>${rows.length} 個受保護服務 · 點選列以展開設定</small></div></div><div class="service-list"><div class="service-list-head"><span></span><span>服務 ID</span><span>服務名稱</span><span>類型</span><span>IP / Port</span><span>WAF</span><span>狀態</span></div>${rows.map(serviceRow).join('')}</div>`;
    }else if(page==='blacklist'){
      const rows=await api('/blacklist'),scopeNames={all:'全部服務',apache:'購物網站',flask:'員工入口',django:'市民服務'};html='<div class="notice">封鎖規則會依指定範圍套用至服務；選擇「全部服務」可一次阻擋三個對外靶機。每次變更都會保存操作紀錄。</div><form id="ban-form" class="ban-form"><input name="ip" required placeholder="要封鎖的 IP" aria-label="要封鎖的 IP"><select name="scope" aria-label="封鎖範圍"><option value="all">全部服務</option><option value="apache">購物網站</option><option value="flask">員工入口</option><option value="django">市民服務</option></select><input name="reason" required maxlength="500" placeholder="封鎖原因" aria-label="封鎖原因"><button>新增封鎖</button></form>';
      html+=panel('已封鎖來源',`${rows.length} 條規則`,rows.length?`<div class="table-wrap"><table><thead><tr><th>來源 IP</th><th>封鎖範圍</th><th>加入時間</th><th>原因</th><th></th></tr></thead><tbody>${rows.map(r=>`<tr><td class="mono">${esc(r.ip)}</td><td>${esc(scopeNames[r.scope||'all']||r.scope)}</td><td>${time(r.added_at)}</td><td>${esc(r.reason)}</td><td><button class="secondary" data-unban="${esc(r.ip)}" data-unban-scope="${esc(r.scope||'all')}">解除封鎖</button></td></tr>`).join('')}</tbody></table></div>`:empty('沒有已封鎖的 IP','調查日誌後，可在此新增需要阻擋的來源。'));
    }else if(page==='rules'){
      const [rows,waf]=await Promise.all([api('/rules'),api('/waf-rules')]),behavior=rows.filter(r=>r.rule_type==='behavior'),correlation=rows.filter(r=>r.rule_type!=='behavior');
      const metrics={request_count:'連線次數',distinct_services:'不同服務數',distinct_paths:'不同 URL 數',status_404_ratio:'404 比例（%）',server_error_count:'5xx 次數',suspicious_method:'異常 HTTP 方法',sensitive_path:'敏感路徑',suspicious_ua:'攻擊工具 User-Agent',multi_attack_types:'不同攻擊類型',intel_match:'威脅情資命中',detector_correlation:'WAF 與 ML 同時命中'};
      const ruleRow=(r,removable)=>`<details class="rule-item"><summary><span class="rule-chevron">›</span><span class="mono rule-id">${esc(r.rule_uid)}</span><strong>${esc(r.display_name||r.name)}</strong><span>${esc(r.metric==='attack_count'?(labels[r.attack]+' 重複命中'):(metrics[r.metric]||r.metric))}</span><span>${num(r.threshold)} / ${num(r.window_sec)} 秒</span><span class="badge ${esc(r.severity)}">${esc(r.severity)}</span><span class="rule-state ${r.enabled?'on':'off'}">${r.enabled?'啟用':'停用'}</span></summary><form class="rule rule-editor" data-rule="${r.id}"><p>${esc(r.description||'尚未提供規則描述')}</p><div class="rule-fields"><label>規則名稱<input name="name" required maxlength="100" value="${esc(r.name)}"></label><label>偵測指標<select name="metric" ${r.rule_type==='behavior'?'':'disabled'}>${Object.entries(metrics).map(([k,v])=>`<option value="${k}" ${r.metric===k?'selected':''}>${v}</option>`).join('')}${r.metric==='attack_count'?`<option value="attack_count" selected>${esc(labels[r.attack])} 重複命中</option>`:''}</select></label><label>門檻值<input name="threshold" type="number" min="1" max="10000" required value="${r.threshold}"></label><label>時間窗（秒）<input name="window_sec" type="number" min="10" max="86400" required value="${r.window_sec}"></label><label>冷卻時間（秒）<input name="cooldown_sec" type="number" min="10" max="86400" required value="${r.cooldown_sec}"></label><label>嚴重度<select name="severity">${['low','medium','high','critical'].map(s=>`<option ${r.severity===s?'selected':''}>${s}</option>`).join('')}</select><label class="rule-enabled">啟用規則<input type="checkbox" name="enabled" ${r.enabled?'checked':''}></label><label class="rule-description">描述<textarea name="description" maxlength="500">${esc(r.description||'')}</textarea></label></div><div class="detail-actions"><button>儲存變更</button>${removable?`<button type="button" class="secondary" data-delete-rule="${r.id}">移除規則</button>`:''}</div></form></details>`;
      const ruleList=(items,removable)=>`<div class="rule-list"><div class="rule-list-head"><span></span><span>規則 ID</span><span>規則名稱</span><span>偵測指標</span><span>門檻／時間窗</span><span>嚴重度</span><span>狀態</span></div>${items.map(r=>ruleRow(r,removable)).join('')}</div>`;
      html='<div class="rule-source-grid"><div class="panel"><h2>ML 分類器</h2><p>Random Forest 將請求分成 SQLi、XSS、路徑穿越或正常。模型本身由訓練流程維護。</p><span class="detector ml">ML</span></div><div class="panel"><h2>WAF 規則集</h2><p>OWASP CRS 4.25 · PL1 · Detection Only。Rule ID 與排除規則由 WAF 設定維護。</p><span class="detector waf">WAF / CRS</span></div><div class="panel"><h2>SIEM 行為規則</h2><p>依來源、服務、流量與時間窗建立告警；即使沒有攻擊 payload 也會觸發。</p><span class="detector both">關聯分析</span></div></div>';
      const wafRows=waf.families.map(r=>`<details class="rule-item waf-rule-item"><summary><span class="rule-chevron">›</span><span class="mono rule-id">${esc(r.rule_range)}</span><strong>${esc(r.name)}</strong><span>${esc(r.category)}</span><span>${num(r.hits)} 次命中</span><span class="badge high">PL${waf.paranoia_level}</span><span class="rule-state on">偵測中</span></summary><div class="rule-editor waf-rule-detail"><p>${esc(r.description)}</p><dl class="detail-grid"><dt>規則來源</dt><dd>${esc(waf.engine)} ${esc(waf.version)}</dd><dt>執行模式</dt><dd>${esc(waf.mode)}</dd><dt>實際命中 Rule ID</dt><dd>${r.observed_rules.length?r.observed_rules.map(x=>`<code>${esc(x.rule_id)}</code> × ${num(x.count)}`).join('、'):'尚無命中紀錄'}</dd><dt>最近命中</dt><dd>${r.observed_rules.length?time(r.observed_rules.reduce((latest,x)=>x.last_seen>latest?x.last_seen:latest,'')):'—'}</dd></dl></div></details>`).join('');
      html+=`<div class="rule-section-title"><div><h2>WAF／OWASP CRS 規則集</h2><small>${waf.families.length} 個規則家族 · ${esc(waf.mode)} · 命中統計取最近 ${num(waf.sample_limit)} 筆 WAF 紀錄</small></div></div><div class="rule-list"><div class="rule-list-head"><span></span><span>Rule ID</span><span>規則家族</span><span>攻擊類型</span><span>實際命中</span><span>層級</span><span>狀態</span></div>${wafRows}</div>`;
      html+=`<details class="panel create-panel"><summary><strong>新增行為規則</strong><small>系統自動配置 USR 規則 ID</small></summary><form id="new-rule-form" class="create-form rule-create-form"><label>名稱<input name="name" required maxlength="100"></label><label class="search">描述<input name="description" maxlength="500"></label><label>偵測指標<select name="metric">${Object.entries(metrics).map(([k,v])=>`<option value="${k}">${v}</option>`).join('')}</select></label><label>門檻<input name="threshold" type="number" min="1" max="10000" value="50" required></label><label>時間窗（秒）<input name="window_sec" type="number" min="10" max="86400" value="60" required></label><label>冷卻（秒）<input name="cooldown_sec" type="number" min="10" max="86400" value="300" required></label><label>嚴重度<select name="severity"><option>low</option><option>medium</option><option selected>high</option><option>critical</option></select></label><button>新增規則</button></form></details>`;
      html+=`<div class="rule-section-title"><div><h2>行為與流量規則</h2><small>${behavior.length} 條規則 · 點選列以展開編輯</small></div></div>${ruleList(behavior,true)}<div class="rule-section-title"><div><h2>攻擊分類關聯規則</h2><small>${correlation.length} 條系統規則 · 可調整或停用</small></div></div>${ruleList(correlation,false)}`;
    }else if(page==='intel'){
      const ip=new URLSearchParams({page:intelFilters.page,sort:intelFilters.sort});if(intelFilters.q)ip.set('q',intelFilters.q);if(intelFilters.kind)ip.set('kind',intelFilters.kind);if(intelFilters.verdict)ip.set('verdict',intelFilters.verdict);const [result,summary]=await Promise.all([api('/intel?'+ip),api('/intel/summary')]);
      html=`<div class="notice">來源 IP 風險清單提供額外調查線索，會和 WAF、ML 與行為規則交叉判斷；不會自動封鎖 IP。</div><div class="intel-feed-bar"><div><strong>免費來源 IP 情資</strong><small>Tor Project · FireHOL Level 1</small></div><span class="risk-feed-label">Tor Exit Nodes · FireHOL Level 1</span>${currentUser.role==="admin"?"<button id=\"sync-intel\">同步風險 IP</button>":""}</div><form id="intel-form" class="ban-form intel-manual-form"><label>類型<select name="kind"><option value="ip">IP</option><option value="domain">網域</option><option value="url">URL</option><option value="hash">Hash</option></select></label><label>情資值<input name="value" required placeholder="例如 203.0.113.10"></label><label>來源<input name="source" value="manual" placeholder="例如手動匯入"></label><label>信心分數<input name="confidence" type="number" min="0" max="100" value="0" placeholder="0–100"></label><label>判定<select name="verdict"><option>unknown</option><option>benign</option><option>suspicious</option><option>malicious</option></select></label><button>加入情資</button></form>`;
      const cards=[['全部情資',summary.total,''],['高信心惡意',summary.malicious,'attack'],['命中目前事件',summary.matched_events,'pending']].map(([label,n,cl])=>`<div class="metric ${cl}"><div class="metric-label">${label}</div><div class="metric-number">${num(n)}</div><small>目前資料庫</small></div>`).join('');
      html='<div class="intel-metrics">'+cards+'</div>'+html;
      html+=panel('IOC 清單',`第 ${intelFilters.page} 頁 · 共 ${num(result.total)} 筆`,`<form id="intel-filter-form" class="filters"><label class="search">搜尋<input name="q" value="${esc(intelFilters.q)}" placeholder="IP、網域、來源或描述"></label><label>類型<select name="kind"><option value="">全部類型</option>${['ip','domain','url','hash'].map(k=>`<option value="${k}" ${intelFilters.kind===k?'selected':''}>${k}</option>`).join('')}</select></label><label>判定<select name="verdict"><option value="">全部判定</option>${['malicious','suspicious','unknown','benign'].map(k=>`<option value="${k}" ${intelFilters.verdict===k?'selected':''}>${k}</option>`).join('')}</select></label><label>排序<select name="sort"><option value="last_seen" ${intelFilters.sort==='last_seen'?'selected':''}>最近更新</option><option value="confidence" ${intelFilters.sort==='confidence'?'selected':''}>信心分數</option><option value="value" ${intelFilters.sort==='value'?'selected':''}>情資值</option></select></label><button>套用篩選</button><button type="button" class="secondary" id="clear-intel-filter">清除</button></form>${result.items.length?`<div class="table-wrap"><table><thead><tr><th>類型</th><th>情資值</th><th>來源</th><th>信心</th><th>判定</th><th>最後出現</th><th></th></tr></thead><tbody>${result.items.map(r=>`<tr><td>${esc(r.kind)}</td><td class="mono">${esc(r.value)}</td><td>${esc(r.source)}</td><td>${r.confidence}/100</td><td><span class="badge ${r.verdict}">${esc(r.verdict)}</span></td><td>${time(r.last_seen)}</td><td><button class="secondary" data-delete-intel="${r.id}">移除</button></td></tr>`).join('')}</tbody></table></div><div class="pagination"><span>每頁 50 筆</span><div><button class="secondary" data-intel-page="${intelFilters.page-1}" ${intelFilters.page<=1?'disabled':''}>上一頁</button><span>${intelFilters.page} / ${Math.max(1,Math.ceil(result.total/50))}</span><button class="secondary" data-intel-page="${intelFilters.page+1}" ${intelFilters.page*50>=result.total?'disabled':''}>下一頁</button></div></div>`:empty('沒有符合條件的情資','調整搜尋或篩選條件。')}`);
    }else if(page==='intel-news'){
      const [news,ips,urls]=await Promise.all([api('/intel/news?page='+intelNewsPage),api('/intel?kind=ip&page=1&sort=last_seen'),api('/intel?kind=url&page=1&sort=last_seen')]);
      const mask=v=>String(v||'').replace(/:\/\//,'[://]').replaceAll('/','／');
      const newsBody=news.items.length?`<div class="news-list">${news.items.map(n=>`<article><small>${esc(n.source)} · ${esc(n.published)}</small><h3>${esc(n.title)}</h3><a href="${esc(n.url)}" target="_blank" rel="noopener noreferrer">查看原文（請先確認來源）</a></article>`).join('')}</div>`:empty('目前無法取得新聞','請檢查網路，或稍後再更新。');
      const intelRows=(rows,label,masked=false)=>rows.items.length?`<div class="masked-list ${masked?'phishing-list':''}">${rows.items.slice(0,20).map(r=>masked?`<div><div class="intel-value-row"><span class="badge ${r.verdict}">${label}</span><code title="${esc(mask(r.value))}">${esc(mask(r.value))}</code></div><small>${esc(r.source)} · 信心 ${r.confidence}/100</small><p>${esc(r.notes||'近期公開釣魚網址')}</p></div>`:`<div><span class="badge ${r.verdict}">${label}</span><code>${esc(r.value)}</code><small>${esc(r.source)} · ${r.confidence}/100</small></div>`).join('')}</div>`:empty('尚無資料','按同步後會顯示在這裡。');
      const newsPages=Number(news.pages||1), newsPage=Number(news.page||intelNewsPage);
      html=`<div class="notice">本頁提供分析師快速掌握近期資安新知、來源 IP 風險與釣魚網站趨勢；釣魚網址採遮罩顯示，避免誤點。${currentUser.role==='admin'?'<button class="secondary" id="sync-all-intel">同步全部情資</button>':''}</div><div class="intel-news-grid">${panel('近期資安新聞',`台灣資安 RSS · 第 ${newsPage} / ${newsPages} 頁`,newsBody+`<div class="pagination"><button class="secondary" data-news-page="${intelNewsPage-1}" ${intelNewsPage<=1?'disabled':''}>上一頁</button><span>${intelNewsPage} / ${newsPages}</span><button class="secondary" data-news-page="${intelNewsPage+1}" ${intelNewsPage>=newsPages?'disabled':''}>下一頁</button></div>`)}${panel('來源 IP 風險清單','Tor Project／FireHOL · IP 完整顯示',intelRows(ips,'來源 IP'))}${panel('近期釣魚網站資訊','OpenPhish · 網址遮罩顯示',intelRows(urls,'釣魚網址',true))}</div>`;
    }else if(page==='assistant'){
      const ai=await api('/ai/settings');
      const context=await api('/ai/context?hours=1'),snap=context.snapshot;
      const settings=currentUser?.role==='admin'?`<details class="panel ai-settings"><summary><strong>AI Provider 設定</strong><small>管理 API key、模型與連線測試</small></summary><form id="ai-settings-form" class="filters"><label>Provider<select name="provider" id="ai-provider"><option value="gemini" ${ai.provider==='gemini'?'selected':''}>Gemini</option><option value="openai" ${ai.provider==='openai'?'selected':''}>OpenAI</option></select></label><label>Model<select name="model" id="ai-model" required>${aiModelOptions(ai.provider,ai.model)}</select></label><label class="search">API key<input name="api_key" type="password" minlength="8" placeholder="留空沿用目前 key（${esc(ai.api_key_masked||'未設定')}）"></label><button>保存設定</button><button type="button" class="secondary" id="test-ai">測試連線</button><span id="ai-feedback" class="ai-feedback" role="status"></span></form></details>`:'';
      html=`<div class="security-context"><div class="context-head"><div><span class="context-eyebrow">即時安全上下文</span><h2>${snap.open_by_severity.critical?'重大風險待處理':snap.incident_status.new||snap.incident_status.investigating?'需要分析人員關注':'監控狀態穩定'}</h2><small>最近 1 小時 · 快照 ${esc(snap.context_version)} · ${time(snap.generated_at)}</small></div><div class="context-metrics"><div><strong>${num(snap.counts.attack_traffic)}</strong><span>攻擊流量</span></div><div><strong>${num((snap.incident_status.new||0)+(snap.incident_status.investigating||0))}</strong><span>待處理事件</span></div><div><strong>${snap.counts.attack_rate}%</strong><span>攻擊比例</span></div></div></div></div>${settings}<div class="assistant-layout"><div class="chat-shell panel"><div class="chat-head"><div><h2>NCU SOC AI 防禦小精靈</h2><small>Enter 送出 · Shift+Enter 換行</small></div><button id="new-chat" class="secondary">＋ 新對話</button></div><div id="chat-messages" class="chat-messages"></div><form id="chat-form" class="chat-input"><textarea name="message" required maxlength="4000" rows="2" placeholder="例如：最近 24 小時攻擊大致如何？封鎖 203.0.113.9"></textarea><button>送出</button></form><div class="prompt-suggestions"><div class="suggestion-head"><span>依目前狀況建議提問</span><small id="suggestion-updated">每次回答後自動更新</small></div><div id="ai-suggestions" class="ai-suggestions">${context.items.map(item=>`<button type="button" class="suggestion-card" data-chat-submit="${esc(item.question)}"><span>${esc(item.title)}</span><strong>${esc(item.question)}</strong><small>${esc(item.reason)}</small></button>`).join('')}</div></div></div><aside class="assistant-help panel"><h3>指令與範例</h3><p><code>/help</code> 顯示完整指令</p><button class="link-button" data-chat-prompt="/status">/status　系統狀態</button><button class="link-button" data-chat-prompt="/logs recent">/logs recent　最近攻擊</button><button class="link-button" data-chat-prompt="/blacklist list">/blacklist list　封鎖清單</button><button class="link-button" data-chat-prompt="/check 1.2.3.4">/check IP 情資</button><button class="link-button" data-chat-prompt="/ban 1.2.3.4">/ban IP</button><button class="link-button" data-chat-prompt="/unban 1.2.3.4">/unban IP</button><hr><h3>舊對話</h3><div id="chat-sessions" class="chat-sessions"></div></aside></div>`;
      setTimeout(()=>loadChat().catch(fail),0);
    }else if(page==='audit'){
      const rows=await api('/audit');html=panel('操作紀錄','最近 100 筆管理操作',rows.length?`<div class="table-wrap"><table><thead><tr><th>時間</th><th>來源</th><th>操作</th><th>內容</th></tr></thead><tbody>${rows.map(r=>`<tr><td>${time(r.timestamp)}</td><td>${esc(r.actor)}</td><td>${esc(r.action)}</td><td class="url-cell" title="${esc(r.detail)}">${esc(r.detail)}</td></tr>`).join('')}</tbody></table></div>`:empty('尚無操作紀錄','規則、事件狀態及封鎖變更會記錄在這裡。'));
    }else if(page==='users'){
      const rows=await api('/users');
      html=`<div class="notice">管理員可建立帳號、調整角色、停用帳號及重設密碼。密碼不會以明文保存。</div><div class="panel"><form id="new-user-form" class="user-create"><label>登入帳號<input name="username" required maxlength="64" placeholder="例如 analyst01"></label><label>顯示名稱<input name="display_name" required maxlength="100"></label><label>初始密碼<input name="password" type="password" required minlength="4" autocomplete="new-password"></label><label>角色<select name="role"><option value="analyst">Analyst</option><option value="admin">管理員</option></select></label><button>新增使用者</button></form></div>${panel('帳號清單',`${rows.length} 個使用者`,`<div class="user-list"><div class="user-list-head"><span>登入帳號</span><span>顯示名稱</span><span>角色</span><span>狀態</span><span>重設密碼／操作</span></div>${rows.map(u=>`<form class="user-row" data-user="${u.id}"><strong>${esc(u.username)}<small>${u.id===currentUser.id?'● 目前登入':''}</small></strong><input name="display_name" required value="${esc(u.display_name)}"><select name="role"><option value="analyst" ${u.role==='analyst'?'selected':''}>Analyst</option><option value="admin" ${u.role==='admin'?'selected':''}>管理員</option></select><label><input name="enabled" type="checkbox" ${u.enabled?'checked':''}> 啟用</label><span class="user-actions"><input name="password" type="password" minlength="4" placeholder="留空則不重設"><button>儲存</button></span></form>`).join('')}</div>`)}`;
    }else if(page==='account'){
      const role=currentUser.role==='admin'?'管理員':'Analyst', initial=(currentUser.display_name||currentUser.username).slice(0,1).toUpperCase();
      const abilities=currentUser.role==='admin'?['管理偵測規則與受保護服務','管理平台使用者及 AI Provider','查看稽核紀錄並使用所有調查功能']:['查看儀表板、日誌與關聯拓樸','調查與處理安全事件','使用情資、封鎖管理及 AI 資安助理'];
      html=`<div class="account-layout"><section class="panel account-card"><div class="account-identity"><span class="account-avatar">${esc(initial)}</span><div><h2>${esc(currentUser.display_name)}</h2><small>@${esc(currentUser.username)} · ${role}</small></div></div><form id="account-form" class="account-form"><label>登入帳號<input value="${esc(currentUser.username)}" disabled></label><label>顯示名稱<input name="display_name" required maxlength="100" value="${esc(currentUser.display_name)}"></label><label>目前密碼<input name="current_password" type="password" autocomplete="current-password" placeholder="只有修改密碼時需要"></label><label>新密碼<input name="new_password" type="password" minlength="4" autocomplete="new-password" placeholder="留空則不修改密碼"></label><label>確認新密碼<input name="confirm_password" type="password" minlength="4" autocomplete="new-password" placeholder="再次輸入新密碼"></label><button>儲存我的帳號</button></form></section><aside class="panel role-card"><h2>目前權限</h2><p><span class="badge ${currentUser.role==='admin'?'high':'investigating'}">${role}</span></p><ul>${abilities.map(x=>`<li>${esc(x)}</li>`).join('')}</ul><small>角色調整需由管理員在使用者管理頁執行。</small></aside></div>`;
    }else if(page==='settings'){
      const s=await api('/settings'),w=s.webhook,p=s.proxy;
      html=`<div class="notice">這裡集中管理與 SIEM 平台本身相關的設定。儲存後會記錄操作者；Webhook 監聽 port 或代理 port 的變更，需重新啟動服務才會套用。</div><form id="system-settings-form"><div class="settings-grid"><section class="panel settings-card"><div class="panel-head"><div><h2>LINE Webhook</h2><small>公開網址由 ngrok 或其他 Tunnel 提供</small></div><span class="badge ${w.active_status==='registered'?'resolved':'medium'}">${esc(w.active_status)}</span></div><div class="settings-fields"><label>目前 Webhook URL<input name="webhook.public_url" value="${esc(w.public_url||w.active_url||'')}" placeholder="https://xxxx.ngrok-free.app/webhook"></label><label>監聽 Host<input name="webhook.listen_host" value="${esc(w.listen_host)}"></label><label>監聽 Port<input name="webhook.listen_port" type="number" min="1024" max="65535" value="${w.listen_port}"></label><label class="check"><input name="webhook.auto_register" type="checkbox" ${w.auto_register?'checked':''}> 啟動時自動向 LINE 登錄 Webhook</label><p class="settings-note">目前生效 URL：<span class="mono">${esc(w.active_url||'尚未記錄')}</span></p></div></section><section class="panel settings-card"><div class="panel-head"><div><h2>反向代理／WAF Gateway</h2><small>目前使用 OWASP CRS；設定概念對應 Nginx upstream</small></div><span class="badge ${p.enabled?'resolved':'false_positive'}">${p.enabled?'啟用':'停用'}</span></div><div class="settings-fields"><label class="check"><input name="proxy.enabled" type="checkbox" ${p.enabled?'checked':''}> 啟用入口代理與 WAF 監控</label><label>代理類型<select name="proxy.type"><option value="modsecurity-crs" ${p.type==='modsecurity-crs'?'selected':''}>ModSecurity + OWASP CRS</option><option value="nginx" ${p.type==='nginx'?'selected':''}>Nginx reverse proxy</option></select></label><label>Apache 對外 Port<input name="proxy.apache_port" type="number" min="1" max="65535" value="${p.apache_port}"></label><label>Flask 對外 Port<input name="proxy.flask_port" type="number" min="1" max="65535" value="${p.flask_port}"></label><label>Django 對外 Port<input name="proxy.django_port" type="number" min="1" max="65535" value="${p.django_port}"></label><label>偵測模式<select name="proxy.mode"><option value="detection_only" ${p.mode==='detection_only'?'selected':''}>Detection Only（只記錄）</option><option value="blocking" ${p.mode==='blocking'?'selected':''}>Blocking（阻擋）</option></select></label><p class="settings-note">現行 Demo Gateway：Apache :${p.apache_port} · Flask :${p.flask_port} · Django :${p.django_port}</p></div></section></div><div class="detail-actions"><button>儲存系統設定</button></div></form>`;
    }
    if(version===requestVersion)$('#content').innerHTML=html;
  }catch(error){if(version===requestVersion)fail(error);}
}
function navigate(){if(!currentUser)return;page=location.hash.slice(1)||'overview';if(!titles[page]||(currentUser.role!=='admin'&&['rules','services','audit','users','settings'].includes(page))){page='overview';location.hash='overview';}$('#title').textContent=titles[page];$('#crumb').textContent=titles[page];document.querySelectorAll('nav a').forEach(a=>a.classList.toggle('active',a.dataset.page===page));$('#range').disabled=!['overview','logs','incidents','topology'].includes(page);render();}
let chatId=null, chatLoading=null;
async function ensureChat(){if(chatId)return chatId;if(!chatLoading){chatLoading=(async()=>{const sessions=await api('/chat/sessions');chatId=sessions[0]?.id||(await api('/chat/sessions',{method:'POST'})).id;})().finally(()=>{chatLoading=null;});}await chatLoading;return chatId;}
async function loadChat(){await ensureChat();const rows=await api('/chat/sessions/'+chatId);const box=$('#chat-messages');if(box)box.innerHTML=rows.length?rows.map(r=>`<div class="chat-msg ${r.role}"><span>${r.role==='user'?'你':'小精靈'}<time>${time(r.created_at)}</time></span><div class="message-body ${r.role==='assistant'?'markdown-body':''}">${r.role==='assistant'?markdown(r.content):esc(r.content).replace(/\n/g,'<br>')}</div></div>`).join(''):'<div class="empty"><strong>從一個問題開始</strong>例如：「最近有哪些攻擊？」</div>';const sessions=await api('/chat/sessions');const list=$('#chat-sessions');if(list)list.innerHTML=sessions.map(s=>`<div class="session-row ${s.id===chatId?'active':''}"><button class="session-item" data-session="${esc(s.id)}"><span>${esc(s.title||'對話')}</span><small>${time(s.updated_at)}</small></button><div class="session-actions"><button type="button" data-rename-session="${esc(s.id)}" data-title="${esc(s.title)}" title="重新命名" aria-label="重新命名">✎</button><button type="button" data-delete-session="${esc(s.id)}" title="刪除對話" aria-label="刪除對話">×</button></div></div>`).join('');}
async function loadMiniChat(){
  await ensureChat();
  const rows=await api('/chat/sessions/'+chatId),box=$('#ai-mini-messages');
if(box)box.innerHTML=rows.length?rows.map(r=>`<div class="ai-mini-message ${r.role}"><time>${r.role==='user'?'你':'小精靈'} · ${time(r.created_at)}</time><div class="message-body ${r.role==='assistant'?'markdown-body':''}">${r.role==='assistant'?markdown(r.content):esc(r.content).replace(/\n/g,'<br>')}</div></div>`).join(''):'<div class="ai-mini-empty">輸入問題開始調查目前的安全狀態。</div>';
  if(box)box.scrollTop=box.scrollHeight;
  const context=await api('/ai/context?hours=1'),suggestions=$('#ai-mini-suggestions');
  if(suggestions)suggestions.innerHTML=context.items.slice(0,3).map(i=>`<button type="button" data-mini-suggestion="${esc(i.question)}">${esc(i.title)}</button>`).join('');
}
async function sendMiniChat(message){
  await ensureChat();
  const box=$('#ai-mini-messages');
  if(box)box.insertAdjacentHTML('beforeend',`<div class="ai-mini-message user"><time>你 · ${time(new Date().toISOString())}</time><p>${esc(message)}</p></div><div class="ai-mini-message assistant" id="mini-typing"><time>AI</time><p>正在分析…</p></div>`);
  if(box)box.scrollTop=box.scrollHeight;
  const reply=await api('/chat/sessions/'+chatId+'/messages',{method:'POST',body:JSON.stringify({message})});
  await loadMiniChat();
  const follow=await api('/ai/suggestions',{method:'POST',body:JSON.stringify({message,answer:reply.content||'',hours:1,session_id:chatId})});
  const suggestions=$('#ai-mini-suggestions');if(suggestions)suggestions.innerHTML=follow.items.slice(0,3).map(i=>`<button type="button" data-mini-suggestion="${esc(i.question)}">${esc(i.title)}</button>`).join('');
}
async function refreshSuggestions(message='',answer=''){
  const target=$('#ai-suggestions');if(!target)return;
  const result=message||answer
    ?await api('/ai/suggestions',{method:'POST',body:JSON.stringify({message,answer,hours:1,session_id:chatId||''})})
    :await api('/ai/context?hours=1');
  target.innerHTML=result.items.map(item=>`<button type="button" class="suggestion-card" data-chat-submit="${esc(item.question)}"><span>${esc(item.title)}</span><strong>${esc(item.question)}</strong><small>${esc(item.reason)}</small></button>`).join('');
  const stamp=$('#suggestion-updated');if(stamp)stamp.textContent='已依快照 '+result.snapshot.context_version+' 更新 · '+time(result.snapshot.generated_at);
}
function openDialog(title,html){$('#detail-title').textContent=title;$('#detail-body').innerHTML=html;if(!$('#detail').open)$('#detail').showModal();}
async function showEvent(id){const r=await api('/events/'+encodeURIComponent(id));openDialog('日誌詳情',`${detector(r)} ${badge(r.attack)}<dl class="detail-grid">${[['發生時間',time(r.timestamp)],['接收時間',time(r.received_at)],['來源 IP',r.src_ip+(r.src_port?':'+r.src_port:'')],['目的地 IP',`${r.dst_ip||r.service_host||'127.0.0.1'}:${r.service_port||80}`],['受保護服務',r.service_name||r.target],['偵測來源',r.origin==='modsecurity-crs'?'WAF / OWASP CRS':'ML 分類器'],['網路協定',`${(r.transport||'tcp').toUpperCase()} / ${(r.protocol||'http').toUpperCase()} ${r.http_version||''}`],['HTTP 狀態',r.status],['回應大小',`${r.response_bytes||0} bytes`],['Parser',r.parser_name||r.origin],['事件 ID',r.id]].map(([k,v])=>`<dt>${k}</dt><dd>${esc(v)}</dd>`).join('')}</dl><h3>請求路徑</h3><pre>${esc(r.method+' '+r.url)}</pre><h3>User-Agent</h3><pre>${esc(r.user_agent||'—')}</pre><h3>Referer</h3><pre>${esc(r.referer||'—')}</pre><h3>原始日誌</h3><pre>${esc(r.raw)}</pre><div class="detail-actions"><button data-ip="${esc(r.src_ip)}">查看此來源日誌</button><button class="secondary" data-ban-prefill="${esc(r.src_ip)}">封鎖此來源</button></div>`);}
async function showIncident(id){const r=await api('/incidents/'+id);openDialog('事件 #'+r.id,`<h3>${esc(r.rule_name)}</h3><dl class="detail-grid"><dt>來源</dt><dd>${esc(r.src_ip)}</dd><dt>命中筆數</dt><dd>${r.count}</dd><dt>首次偵測</dt><dd>${time(r.first_seen)}</dd><dt>最後偵測</dt><dd>${time(r.last_seen)}</dd><dt>目前狀態</dt><dd>${esc(statusNames[r.status]||r.status)}</dd><dt>最後處理者</dt><dd>${esc(r.handled_by||'未記錄（舊資料）')}</dd><dt>處理時間</dt><dd>${r.handled_at?time(r.handled_at):'—'}</dd><dt>通知</dt><dd>${r.notifications.length?r.notifications.map(n=>`${esc(n.status)}（嘗試 ${n.attempts} 次）`).join('<br>'):'未配置通知對象'}</dd></dl><form id="incident-edit" data-id="${r.id}"><label class="note-label">處理狀態</label><select name="status">${Object.entries(statusNames).map(([k,v])=>`<option value="${k}" ${r.status===k?'selected':''}>${v}</option>`).join('')}</select><label class="note-label">調查註記</label><textarea name="note" maxlength="4000">${esc(r.note)}</textarea><div class="detail-actions"><button>儲存處理結果</button><button type="button" class="secondary" data-ban-prefill="${esc(r.src_ip)}">封鎖來源</button></div></form><h3>關聯證據（最多顯示 200 筆）</h3>${tableEvents(r.events)}`);}
document.addEventListener('click',async e=>{const b=e.target.closest('button,a,[data-ip]');if(!b)return;try{
  if(b.dataset.topologyMode){topologyMode=b.dataset.topologyMode;await render();return;}
  if(b.dataset.event)await showEvent(b.dataset.event);
  if(b.dataset.incident)await showIncident(b.dataset.incident);
  if(b.dataset.ip){logFilters={q:'',src_ip:b.dataset.ip,attack:'',status:'',since:'',until:''};logPage=1;$('#detail').close();location.hash='logs';if(page==='logs')render();}
  if(b.dataset.banPrefill){$('#detail').close();location.hash='blacklist';await new Promise(r=>setTimeout(r,150));const input=$('#ban-form input[name=ip]');if(input){input.value=b.dataset.banPrefill;$('#ban-form input[name=reason]').focus();}}
  if(b.dataset.unban){await api('/blacklist/'+encodeURIComponent(b.dataset.unban)+'?scope='+encodeURIComponent(b.dataset.unbanScope||'all'),{method:'DELETE'});toast('已解除封鎖');await render();}
  if(b.dataset.deleteIntel){await api('/intel/'+b.dataset.deleteIntel,{method:'DELETE'});toast('情資已移除');await render();}
  if(b.dataset.intelPage){intelFilters.page=Math.max(1,Number(b.dataset.intelPage));await render();}
  if(b.dataset.newsPage){intelNewsPage=Math.max(1,Number(b.dataset.newsPage));await render();}
  if(b.id==='sync-intel'){b.disabled=true;const result=await api('/intel/sync/risk-ips',{method:'POST'});const counts=Object.values(result).map(x=>x.count||0).reduce((a,n)=>a+n,0);toast(`風險 IP 同步完成：${counts} 筆`);await render();}
  if(b.id==='sync-phishing'){b.disabled=true;const result=await api('/intel/sync/phishing',{method:'POST'});toast(`釣魚網站清單同步完成：${result.count} 筆`);await render();}
  if(b.id==='sync-all-intel'){b.disabled=true;const result=await api('/intel/sync/all',{method:'POST'});const ipCount=Object.values(result.risk_ips||{}).map(x=>x.count||0).reduce((a,n)=>a+n,0);toast(`情資同步完成：風險 IP ${ipCount} 筆、釣魚 ${result.phishing?.count||0} 筆、新聞 ${result.news?.count||0} 筆`);await render();}
  if(b.dataset.deleteRule){if(window.confirm('確定移除此規則？')){await api('/rules/'+b.dataset.deleteRule,{method:'DELETE'});toast('規則已移除');await render();}}
  if(b.dataset.deleteService){if(window.confirm('確定移除此受保護服務？歷史日誌與事件會保留。')){await api('/protected-services/'+b.dataset.deleteService,{method:'DELETE'});toast('受保護服務已移除');await render();}}
  if(b.id==='new-chat'){chatId=(await api('/chat/sessions',{method:'POST'})).id;await loadChat();}
  if(b.dataset.renameSession){const title=window.prompt('對話名稱（最多 80 字）',b.dataset.title);if(title?.trim()){await api('/chat/sessions/'+b.dataset.renameSession,{method:'PATCH',body:JSON.stringify({title:title.trim()})});await loadChat();}}
  if(b.dataset.deleteSession&&window.confirm('確定刪除這則對話？')){await api('/chat/sessions/'+b.dataset.deleteSession,{method:'DELETE'});if(chatId===b.dataset.deleteSession)chatId=null;await loadChat();}
  if(b.dataset.session){chatId=b.dataset.session;await loadChat();}
  if(b.dataset.chatPrompt){const box=$('#chat-form textarea');if(box){box.value=b.dataset.chatPrompt;box.focus();}}
  if(b.dataset.chatSubmit){const box=$('#chat-form textarea');if(box){box.value=b.dataset.chatSubmit;box.form.requestSubmit();}}
  if(b.dataset.trafficMode){trafficMode=b.dataset.trafficMode;await render();}
  if(b.dataset.mapMode){mapMode=b.dataset.mapMode;await render();}
  if(b.id==='test-ai'){const result=await api('/ai/test',{method:'POST'});const feedback=$('#ai-feedback');if(feedback){feedback.textContent='✓ '+(result.reply||'AI 連線成功');feedback.className='ai-feedback success';}toast('AI 連線成功');}
  if(b.dataset.logPage){logPage=Number(b.dataset.logPage);await render();}
  if(b.dataset.incidentPage){incidentPage=Number(b.dataset.incidentPage);await render();}
  if(b.id==='clear-filters'){logFilters={q:'',src_ip:'',attack:'',status:'',since:'',until:''};logPage=1;await render();}
}catch(error){if(b.id==='test-ai'){const feedback=$('#ai-feedback');if(feedback){feedback.textContent='✕ '+error.message;feedback.className='ai-feedback error-text';}}fail(error);toast(error.message);}});
document.addEventListener('keydown',e=>{if((e.key==='Enter'||e.key===' ')&&e.target.matches('[data-ip]')){e.preventDefault();e.target.dispatchEvent(new MouseEvent('click',{bubbles:true}));}});
document.addEventListener('submit',async e=>{e.preventDefault();const form=e.target,data=Object.fromEntries(new FormData(form));const button=form.querySelector('button');if(button)button.disabled=true;try{
  if(form.id==='log-search'){logFilters=data;logPage=1;await render();}
  if(form.id==='intel-filter-form'){intelFilters={...intelFilters,q:data.q||'',kind:data.kind||'',verdict:data.verdict||'',sort:data.sort||'last_seen',page:1};await render();}
  if(form.id==='ban-form'){await api('/blacklist',{method:'POST',body:JSON.stringify(data)});toast('已更新 Apache 封鎖規則');await render();}
  if(form.dataset.rule){data.enabled=form.elements.enabled.checked;for(const k of ['threshold','window_sec','cooldown_sec'])data[k]=Number(data[k]);await api('/rules/'+form.dataset.rule,{method:'PUT',body:JSON.stringify(data)});toast('規則已儲存');await render();}
  if(form.id==='new-rule-form'){data.enabled=true;for(const k of ['threshold','window_sec','cooldown_sec'])data[k]=Number(data[k]);const made=await api('/rules',{method:'POST',body:JSON.stringify(data)});toast(`已新增 ${made.rule_uid}`);await render();}
  if(form.dataset.service){data.port=Number(data.port);data.enabled=form.elements.enabled.checked;data.waf_enabled=form.elements.waf_enabled.checked;await api('/protected-services/'+form.dataset.service,{method:'PUT',body:JSON.stringify(data)});toast('服務設定已更新');await render();}
  if(form.id==='new-service-form'){data.port=Number(data.port);data.enabled=form.elements.enabled.checked;data.waf_enabled=form.elements.waf_enabled.checked;const made=await api('/protected-services',{method:'POST',body:JSON.stringify(data)});toast(`已新增 ${made.service_uid}`);await render();}
  if(form.id==='incident-edit'){await api('/incidents/'+form.dataset.id,{method:'PATCH',body:JSON.stringify(data)});toast('事件已更新');$('#detail').close();await render();}
  if(form.id==='intel-form'){data.confidence=Number(data.confidence);await api('/intel',{method:'POST',body:JSON.stringify(data)});toast('情資已加入');await render();}
  if(form.id==='chat-form'){await ensureChat();const message=data.message;form.elements.message.value='';const box=$('#chat-messages');if(box){box.insertAdjacentHTML('beforeend','<div class="chat-msg user"><span>你</span><p>'+esc(message)+'</p></div><div class="chat-msg assistant typing"><span>AI</span><p><span class="typing-dots">...</span></p></div>');box.scrollTop=box.scrollHeight;}const reply=await api('/chat/sessions/'+chatId+'/messages',{method:'POST',body:JSON.stringify({message})});await loadChat();await refreshSuggestions(message,reply.content||'');}
  if(form.id==='ai-settings-form'){const saved=await api('/ai/settings',{method:'PUT',body:JSON.stringify(data)});toast(`已設定 ${saved.provider} / ${saved.model}`);await render();}
  if(form.id==='new-user-form'){await api('/users',{method:'POST',body:JSON.stringify(data)});toast('使用者已新增');form.reset();await render();}
  if(form.dataset.user){data.enabled=form.elements.enabled.checked;await api('/users/'+form.dataset.user,{method:'PUT',body:JSON.stringify(data)});toast('使用者設定已更新');await render();}
  if(form.id==='account-form'){if(data.new_password!==data.confirm_password)throw new Error('兩次輸入的新密碼不一致');delete data.confirm_password;const result=await api('/auth/account',{method:'PUT',body:JSON.stringify(data)});if(result.signed_out){showLogin();toast('密碼已更新，請重新登入');}else{currentUser=await api('/auth/me');await startSession();toast('個人資料已更新');}}
  if(form.id==='system-settings-form'){const out={webhook:{},proxy:{}};for(const [key,value] of Object.entries(data)){const [group,name]=key.split('.');out[group][name]=value;}out.webhook.listen_port=Number(out.webhook.listen_port);for(const k of ['apache_port','flask_port','django_port'])out.proxy[k]=Number(out.proxy[k]);out.webhook.auto_register=form.elements['webhook.auto_register'].checked;out.proxy.enabled=form.elements['proxy.enabled'].checked;await api('/settings',{method:'PUT',body:JSON.stringify(out)});toast('系統設定已儲存');await render();}
}catch(error){if(form.id==='chat-form'){const feedback=$('#ai-feedback');if(feedback){feedback.textContent='✕ 傳送失敗：'+error.message;feedback.className='ai-feedback error-text';}}fail(error);toast(error.message);}finally{if(button)button.disabled=false;}});
document.addEventListener('change',e=>{if(e.target.id==='incident-status'){incidentStatus=e.target.value;incidentPage=1;render();}if(e.target.id==='ai-provider'){const model=$('#ai-model');if(model)model.innerHTML=aiModelOptions(e.target.value,e.target.value==='gemini'?'gemini-3.5-flash-lite':'gpt-4o-mini');}});
document.addEventListener('click',e=>{if(e.target.id==='clear-intel-filter'){intelFilters={q:'',kind:'',verdict:'',page:1,sort:'last_seen'};render();}});
$('#ai-fab').onclick=async()=>{$('#ai-drawer').hidden=false;try{await loadMiniChat();}catch(error){toast(error.message);}};
$('#ai-drawer-close').onclick=()=>{$('#ai-drawer').hidden=true;};
document.addEventListener('click',e=>{const b=e.target.closest('[data-mini-suggestion]');if(b){const form=$('#ai-mini-form'),box=form?.elements.message;if(box){box.value=b.dataset.miniSuggestion;box.focus();}}});
$('#ai-mini-form').addEventListener('submit',async e=>{e.preventDefault();const form=e.target,message=form.elements.message.value.trim();if(!message)return;form.elements.message.value='';const button=form.querySelector('button');button.disabled=true;try{await sendMiniChat(message);}catch(error){toast(error.message);}finally{button.disabled=false;}});
document.addEventListener('keydown',e=>{if(e.key==='Enter'&&!e.shiftKey&&e.target.matches('#chat-form textarea')){e.preventDefault();e.target.form.requestSubmit();}});
function configureSession(info){
  if(!info)return;
  const last=Date.parse(info.last_activity_at),idle=Number(info.idle_timeout_seconds||1800)*1000;
  sessionDeadline=last+idle;sessionAbsoluteDeadline=Date.parse(info.absolute_expires_at);
  sessionWarningSeconds=Number(info.warning_seconds||300);lastActivityReport=last;sessionExpired=false;updateSessionCountdown();
}
function updateSessionCountdown(){
  const box=$('#session-countdown');if(!box)return;
  if(!currentUser||!sessionDeadline){box.querySelector('strong').textContent='--:--';box.classList.remove('warning','critical');return;}
  const remaining=Math.max(0,Math.min(sessionDeadline,sessionAbsoluteDeadline)-Date.now()),seconds=Math.ceil(remaining/1000);
  box.querySelector('strong').textContent=`${String(Math.floor(seconds/60)).padStart(2,'0')}:${String(seconds%60).padStart(2,'0')}`;
  box.classList.toggle('warning',seconds>60&&seconds<=sessionWarningSeconds);box.classList.toggle('critical',seconds<=60);
  if(seconds<=0&&!sessionExpired){sessionExpired=true;showLogin('登入已因閒置逾期，請重新登入');}
}
async function reportActivity(){
  if(!currentUser||sessionExpired)return;
  const now=Date.now(),idleMs=Number(currentUser.session?.idle_timeout_seconds||1800)*1000;
  sessionDeadline=Math.min(now+idleMs,sessionAbsoluteDeadline);updateSessionCountdown();
  if(now-lastActivityReport<60000)return;
  lastActivityReport=now;
  try{const info=await api('/auth/activity',{method:'POST'});currentUser.session=info;configureSession(info);}
  catch(error){if(currentUser)toast(error.message);}
}
function showLogin(message=''){currentUser=null;sessionDeadline=0;sessionAbsoluteDeadline=0;$('#login-screen').hidden=false;$('#session-countdown')?.classList.remove('warning','critical');if(message)$('#login-error').textContent=message;updateSessionCountdown();}
async function startSession(){
  try{currentUser=await api('/auth/me');configureSession(currentUser.session);$('#login-screen').hidden=true;const role=currentUser.role==='admin'?'管理員':'Analyst';$('#signed-user').textContent=currentUser.display_name;$('#signed-role').textContent=role;$('#top-user').textContent=currentUser.display_name;$('#top-role').textContent='@'+currentUser.username+' · '+role;document.querySelectorAll('[data-admin]').forEach(el=>el.hidden=currentUser.role!=='admin');const toolsNav=document.querySelector('nav[aria-label="調查工具"]');if(toolsNav&&!toolsNav.querySelector('[data-page="intel-news"]'))toolsNav.insertAdjacentHTML('beforeend','<a href="#intel-news" data-page="intel-news"><span>▤</span>資安動態</a>');navigate();}
  catch{showLogin();}
}
$('#login-form').addEventListener('submit',async e=>{e.preventDefault();const form=e.target,button=form.querySelector('button');button.disabled=true;$('#login-error').textContent='';try{currentUser=await api('/auth/login',{method:'POST',body:JSON.stringify(Object.fromEntries(new FormData(form)))});form.reset();await startSession();}catch(error){$('#login-error').textContent=error.message;}finally{button.disabled=false;}});
$('#logout').onclick=async()=>{try{await api('/auth/logout',{method:'POST'});}finally{showLogin();}};
$('#top-logout').onclick=async()=>{try{await api('/auth/logout',{method:'POST'});}finally{showLogin();}};
$('#close-detail').onclick=()=>$('#detail').close();$('#refresh').onclick=()=>render();$('#range').onchange=()=>{logPage=1;render();};window.addEventListener('hashchange',navigate);
setInterval(()=>{if(['overview','topology'].includes(page)&&!$('#detail').open&&!document.hidden)render();},15000);
setInterval(updateSessionCountdown,1000);
['pointerdown','keydown','touchstart','scroll'].forEach(name=>window.addEventListener(name,reportActivity,{passive:true}));
startSession();
